name: Build Image Azure Virtual Desktop

on: workflow_dispatch



jobs:

  Buid_Image_AVD:
    runs-on: windows-2019

    steps:

      - name : Prerequis
        run: |
          Import-Module Az.Accounts
