name: Deploiement AVD & Bicep
on: workflow_dispatch
env:
  LOCATION: "westeurope"
jobs:
  Test_Template_Bicep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo 
        uses: actions/checkout@v2

      - name: Login Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Lint template main.bicep
        run: |
          az bicep build --file ./Bicep/main.bicep

      - name: Creation du temp d'expiration du Token (host Pool)
        shell: pwsh
        run: |
          $Expiration=$((get-date).ToUniversalTime().AddHours(2).ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ'))
          echo "::set-output name=content::$($Expiration)"
        id: var_expiration

      - name: Test du temp d'expiration du Token (host Pool)
        run: |
          echo "The string is: ${{ steps.var_expiration.outputs.content }}"

      - name: Validation du template Bicep
        run: |
          az deployment sub validate \
            --location ${{ env.LOCATION }} \
            --template-file ./Bicep/main.bicep \
            --parameters ./Bicep/parameters/deploy.parameters.json \
            'tokenExpirationTime=${{ steps.var_expiration.outputs.content }}' \
            'pwdLocal=${{ secrets.AZURE_PWD_LOCAL }}' \
            'domainUsernamePassword=${{ secrets.AZURE_DOMAIN_USERNAME_PASSWORD }}'

      - name: What If du template Bicep
        run: |
          az deployment sub what-if \
            --location ${{ env.LOCATION }} \
            --template-file ./Bicep/main.bicep \
            --parameters ./Bicep/parameters/deploy.parameters.json \
            'tokenExpirationTime=${{ steps.var_expiration.outputs.content }}' \
            'pwdLocal=${{ secrets.AZURE_PWD_LOCAL }}' \
            'domainUsernamePassword=${{ secrets.AZURE_DOMAIN_USERNAME_PASSWORD }}'

  Infra_Deployment:
    runs-on: ubuntu-latest
    needs: Test_Template_Bicep
    environment:
      name: Deployment
    
    steps:
      - name: Checkout du repo 
        uses: actions/checkout@v2

      - name: Login Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Creation du temp d'expiration du Token (host Pool)
        shell: pwsh
        run: |
          $Expiration=$((get-date).ToUniversalTime().AddHours(2).ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ'))
          echo "::set-output name=content::$($Expiration)"
        id: var_expiration

      - name: Test du temp d'expiration du Token (host Pool)
        run: |
          echo "The string is: ${{ steps.var_expiration.outputs.content }}"

      - name: Validation du template Bicep
        run: |
          az deployment sub create \
            --location ${{ env.LOCATION }} \
            --template-file ./Bicep/main.bicep \
            --parameters ./Bicep/parameters/deploy.parameters.json \
            'tokenExpirationTime=${{ steps.var_expiration.outputs.content }}' \
            'pwdLocal=${{ secrets.AZURE_PWD_LOCAL }}' \
            'domainUsernamePassword=${{ secrets.AZURE_DOMAIN_USERNAME_PASSWORD }}'