name: Trigger Workflow after "Close issue" comment

on:
  issue_comment:
    branches:
      - main
    path: .github/workflows/3_close_issue.yml
    message: Ok check image

jobs:
  
  Test:
    runs-on: ubuntu-latest  
    check_image:

    steps:

      - name: Login to Azure
        uses: Azure/login@v1
        with:        
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Check Image
        run: |
          Latest=$(az vm image list \
            --location westeurope \
            --publisher MicrosoftWindowsDesktop \
            --offer office-365 \
            --sku evd \
            --all \
            --query "[?sku=='${{ env.SKU'].version" \
            --output tsv | sort -u | tail -n 1)
          echo "::set-output name=version::$Latest"