name: Trigger Workflow after "Close issue" comment

on:
  issue_comment:
    branches:
      - main
    path: .github/workflows/3_close_issue.yml
    message: Ok check image

jobs:
  
  build:
    runs-on: ubuntu-latest
  
    steps:
     - name: Run a one-line script
       run: echo Issue 


    
