name: Deploiement d'une infra Azure Virtual Desktop

on: workflow_dispatch


jobs:

  Test_Template_Bicep:
    runs-on: ubuntu-latest

    steps:
      - name: Creation du temp d'expiration du Token (host Pool)
        shell: pwsh
        run: |
          $Expiration=$((get-date).ToUniversalTime().AddHours(2).ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ'))
          echo "::set-output name=content::$($Expiration)"
        id: var_expiration 