name: Deploiement d'une infra Azure Virtual Desktop

on: workflow_dispatch

env:
  LOCATION: westeurope

jobs:

  Test_Template_Bicep:
    runs-on: ubuntu-latest

    steps:
      - name: Creation du temp d'expiration du Token (host Pool)
        shell: pwsh
        run: |
          $Expiration=$((get-date).ToUniversalTime().AddHours(2).ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ'))
          echo "::set-output name=content::$($Expiration)"
        id: var_expiration

      - name: Test du temp d'expiration du Token (host Pool)
        run: |
          echo "The string is: ${{ steps.var_expiration.outputs.content }}"

      - uses: actions/checkout@v2

      - name: Login Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Test du Template ARM
        run: |
          az deployment sub create --location ${{ env.LOCATION}} \
            --template-file ./Bicep/main.bicep \
            --parameters ./Bicep/deploy.parameters.json 'tokenExpirationTime=${{ steps.var_expiration.outputs.content }}'


               
