name: Build Image Azure Virtual Desktop
on:
  push:
    branches :
      - Pierrc-Dev-One 

env:
  LOCATION: "westeurope"
  RG_NAME_IMAGE: "Rg-AVD-Images-008"

  IMAGE_TEMPLATE_Name: "wvd10ImageTemplate00"
  SIG_NAME: "myaibsig01"
  IMAGE_DEF_NAME: "win10avdsep"

jobs:

  Prerequis_Image_Azure_Virtual_Desktop:
    
    runs-on: windows-2019

    steps:

      - name: Login en PowerShell dans l'abonnement Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true

      - name: Installation des modules PowerShell
        run: |
          'Az.ImageBuilder', 'Az.ManagedServiceIdentity', 'Az.Resources' | ForEach-Object {Install-Module -Name $_ -AllowPrerelease -Force}

      - name: Prérequis 'Ajout Ressource Groupe' & 'Managed Identity' & 'Custom role'
        run: |
          # Creation du 'RG'
          $imageResourceGroup="${{ env.RG_NAME_IMAGE }}"
          $location="${{ env.LOCATION }}"
          New-AzResourceGroup -Name $imageResourceGroup -Location $location

          # Creation d'une 'Manage Identity'
          $currentAzContext = Get-AzContext
          $subscriptionID=$currentAzContext.Subscription.Id
          $timeInt=$(get-date -UFormat "%s")
          $imageRoleDefName="Azure Image Builder Image Def"+$timeInt
          $idenityName="aibIdentity"+$timeInt
          New-AzUserAssignedIdentity -ResourceGroupName $imageResourceGroup -Name $idenityName

          # Recuperation d'un 'Custom Role & Modification de Custom Role & Atribution du Custome Role à la Managed Identity'
          # $idenityNameResourceId=$(Get-AzUserAssignedIdentity -ResourceGroupName $imageResourceGroup -Name $idenityName).Id
          $idenityNamePrincipalId=$(Get-AzUserAssignedIdentity -ResourceGroupName $imageResourceGroup -Name $idenityName).PrincipalId
          $aibRoleImageCreationUrl="https://raw.githubusercontent.com/azure/azvmimagebuilder/master/solutions/12_Creating_AIB_Security_Roles/aibRoleImageCreation.json"
          $aibRoleImageCreationPath = "aibRoleImageCreation.json"
          Invoke-WebRequest -Uri $aibRoleImageCreationUrl -OutFile $aibRoleImageCreationPath -UseBasicParsing
          ((Get-Content -path $aibRoleImageCreationPath -Raw) -replace '<subscriptionID>', $subscriptionID) | Set-Content -Path $aibRoleImageCreationPath
          ((Get-Content -path $aibRoleImageCreationPath -Raw) -replace '<rgName>', $imageResourceGroup) | Set-Content -Path $aibRoleImageCreationPath
          ((Get-Content -path $aibRoleImageCreationPath -Raw) -replace 'Azure Image Builder Service Image Creation Role', $imageRoleDefName) | Set-Content -Path $aibRoleImageCreationPath
          New-AzRoleDefinition -InputFile  .\aibRoleImageCreation.json
          New-AzRoleAssignment -ObjectId $idenityNamePrincipalId -RoleDefinitionName $imageRoleDefName -Scope "/subscriptions/$subscriptionID/resourceGroups/$imageResourceGroup"

