name: Test Run AIB
on:  workflow_dispatch 

env:
  LOCATION: "westeurope"
  RG_NAME_IMAGE: "Rg-AVD-Images-0020"

  IMAGE_TEMPLATE_Name: "avd10ImageTemplate20"
  SIG_NAME: "myaibsig01"
  IMAGE_DEF_NAME: "win10avdoct"
  SHARE_LOCATION: "myfilestorage.file.core.windows.net"
  SHARE_FOLDER: "fslogix"

jobs:
  Run_AIB:
    runs-on: windows-2019
    steps:

      - name: Log in with Azure
        uses: azure/login@v1
        with:
             creds: '${{ secrets.AZURE_CREDENTIALS }}'
             enable-AzPSSession: true  

    
      - name: Download Repo content for template
        uses: actions/checkout@v2


      - name: Configure submit and build template
        run: |
            'Az.Accounts', "Az.Resources", "Az.ImageBuilder", "Az.ManagedServiceIdentity" | ForEach-Object {Install-Module -Name $_ -AllowPrerelease -Force}            
            $currentAzContext = Get-AzContext
            $aibidentityname = Get-AzUserAssignedIdentity -ResourceGroupName "${{ env.RG_NAME_IMAGE }}"
            Start-sleep -Seconds 120
            $aibname = $aibidentityname.Name
            $aibname
            