name: Test
on:  workflow_dispatch 

env:
  LOCATION: "westeurope"
  RG_NAME_IMAGE: "Rg-AVD-Images-0009"

  IMAGE_TEMPLATE_Name: "wvd10ImageTemplate00"
  SIG_NAME: "myaibsig01"
  IMAGE_DEF_NAME: "win10avdsep"
  SHARE_LOCATION: "myfilestorage.file.core.windows.net"
  SHARE_FOLDER: "fslogix"

jobs:

  Prerequis_Image_Azure_Virtual_Desktop:
    
    runs-on: windows-2019

    steps:

      - name: Login en PowerShell dans l'abonnement Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true

      - name: Configure submit and build template
        run: |
           'Az.Accounts', "Az.Resources", "Az.ImageBuilder", "Az.ManagedServiceIdentity" | ForEach-Object {Install-Module -Name $_ -AllowPrerelease -Force}            
            $currentAzContext = Get-AzContext
            $aibidentityname = Get-AzUserAssignedIdentity -ResourceGroupName ${{ env.RG_NAME_IMAGE }}
            $aibidentityname.Name
            $idenityNameResourceId="/subscriptions/"+$subscriptionID+"/resourceGroups/"+$imageResourceGroup+"/providers/Microsoft.ManagedIdentity/userAssignedIdentities/"+$aibidentityname.Name
            $idenityNameResourceId